#!/usr/bin/env bash
# Builds the SwiftPM executable in release mode and wraps it in a proper
# `.app` bundle so macOS Notification Center will accept banners from it.
#
# Usage:
#   ./build-app.sh                          # host-arch only (fast dev loop)
#   ./build-app.sh --install                # copy to /Applications
#   ./build-app.sh --universal              # arm64 + x86_64 fat binary
#   ./build-app.sh --universal --install    # combine

set -euo pipefail

cd "$(dirname "$0")"

APP_NAME="GH Notifier"
BUNDLE_DIR="${APP_NAME}.app"
EXEC_NAME="GHNotifier"

# ---------- parse flags ----------
INSTALL=false
UNIVERSAL=false
for arg in "$@"; do
    case "$arg" in
        --install)   INSTALL=true ;;
        --universal) UNIVERSAL=true ;;
        -h|--help)
            sed -n '2,8p' "$0"; exit 0 ;;
        *)
            echo "Unknown argument: $arg" >&2
            exit 1 ;;
    esac
done

# ---------- swift build ----------
BUILD_ARGS=(build -c release)
if $UNIVERSAL; then
    BUILD_ARGS+=(--arch arm64 --arch x86_64)
fi

echo "==> swift ${BUILD_ARGS[*]}"
swift "${BUILD_ARGS[@]}"

BIN_PATH="$(swift "${BUILD_ARGS[@]}" --show-bin-path)/${EXEC_NAME}"
if [[ ! -x "${BIN_PATH}" ]]; then
    echo "Built binary not found at ${BIN_PATH}" >&2
    exit 1
fi

# ---------- assemble bundle ----------
echo "==> Assembling ${BUNDLE_DIR}"
rm -rf "${BUNDLE_DIR}"
mkdir -p "${BUNDLE_DIR}/Contents/MacOS"
mkdir -p "${BUNDLE_DIR}/Contents/Resources"
cp "${BIN_PATH}"            "${BUNDLE_DIR}/Contents/MacOS/${EXEC_NAME}"
cp "Resources/Info.plist"   "${BUNDLE_DIR}/Contents/Info.plist"

# Icon — generated by scripts/make-icon.sh. If missing, the bundle falls
# back to macOS's generic app icon and Info.plist's CFBundleIconFile is
# effectively a no-op.
if [[ -f "Resources/AppIcon.icns" ]]; then
    cp "Resources/AppIcon.icns" "${BUNDLE_DIR}/Contents/Resources/AppIcon.icns"
else
    echo "==> Note: Resources/AppIcon.icns not found; run ./scripts/make-icon.sh to generate it."
fi

if $UNIVERSAL; then
    echo "==> Bundle slices:"
    lipo -archs "${BUNDLE_DIR}/Contents/MacOS/${EXEC_NAME}" | sed 's/^/    /'
fi

# Sign with a stable self-signed cert so usernoted caches the icon consistently.
# Falls back to ad-hoc if the cert is absent (other machines, CI).
SIGN_ID="GH Notifier Code Signing"
if command -v codesign >/dev/null 2>&1; then
    if security find-identity -v -p codesigning 2>/dev/null | grep -qF "$SIGN_ID"; then
        echo "==> codesign --force --deep --sign \"$SIGN_ID\""
        codesign --force --deep --sign "$SIGN_ID" "${BUNDLE_DIR}" >/dev/null
    else
        echo "==> codesign --force --deep --sign - (ad-hoc fallback)"
        codesign --force --deep --sign - "${BUNDLE_DIR}" >/dev/null
    fi
fi

echo
echo "Built ${BUNDLE_DIR}"
echo

if $INSTALL; then
    DEST="/Applications/${BUNDLE_DIR}"
    echo "==> Installing to ${DEST}"
    rm -rf "${DEST}"
    cp -R "${BUNDLE_DIR}" "${DEST}"
    echo "Installed."
    echo "Launch with: open -a \"${APP_NAME}\""
else
    echo "Launch with: open \"${BUNDLE_DIR}\""
    echo "Or install:  ./build-app.sh --install"
fi
